services:
  wg-manager:
    build:
      context: .
      # network: host
    container_name: wg-manager
    restart: unless-stopped
    ports:
      - "3000:3000"
    # network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    volumes:
      - ./data:/app/data
      - /etc/wireguard:/etc/wireguard
      - ./public:/app/public
networks:
  appnet:
    driver: bridge
    enable_ipv6: true
